---
 homebrew_cask_packages:
  - keepassx0
  - google-drive
  - viscosity


 temp_undo:
  - alfred
  - appcleaner
  - bettertouchtool
  - dropbox
  - google-chrome
  - firefox
  - opera
  - sublime-text3
  - iterm2
  - virtualbox
  - vagrant
  - sourcetree
  - xquartz
  - sequel-pro
  - mysqlworkbench
  - skype
  - skitch
  - imageoptim
  - vlc
  - ifunbox
  - the-unarchiver
  - qlstephen
  - qlmarkdown
  - quicklook-csv
  - quicklook-json
  - qlcolorcode
