# Set up all the python environment, pyenv already installed
---
  - name: build pythons
    command: pyenv install "{{ item }}"
    environment:
      PYTHON_CONFIGURE_OPTS: "{{ lookup('env', 'PYTHON_CONFIGURE_OPTS')}} --enable-framework"
    args:
        creates: "{{ lookup('env', 'HOME') }}/.pyenv/versions/{{ item }}"
    with_items: pyenv_versions

  - name: set default versions
    command: pyenv global {{ pyenv_default_versions }}

  - name: create virtual envs
    command: pyenv virtualenv {{ item.name }}
    args:
        creates: "{{ lookup('env', 'HOME') }}/.pyenv/versions/{{ item.name }}"
    with_items: pyenv_virtualenvs
  - name: verify pip (i.e. fix if broken)
    command: easy_install pip


  - name: populate venvs (3 steps)
    copy: src=roles/python/files/{{ item.req_file }} dest=/tmp/{{ item.req_file }}
    with_items: pyenv_virtualenvs
  - shell: PYENV_VERSION={{ item.name }}  pip install -r /tmp/{{ item.req_file }}
    with_items: pyenv_virtualenvs
  - file: dest=/tmp/{{ item.req_file }} state=absent
    with_items: pyenv_virtualenvs
