# Set up all the python environment, pyenv already installed
---
  - name: build pythons
    command: pyenv install "{{ item }}"
    args:
        creates: "{{ lookup('env', 'HOME') }}/.pyenv/versions/{{ item }}"
    with_items: pyenv_versions

