# Note: default packages are set in ../files/*txt
---
  pyenv_versions:
    - 3.4.5
    # - pypy-2.5.1
    # - 3.5.2
    # - 3.3.6

  pyenv_virtualenvs:
    - { name: 'system', req_file: main-req.txt }
    - { name: 'fabric', req_file: fabric-req.txt }

  pyenv_default_versions:
      3.5.2 system 
