# Set up all the vim environment
---
  - name: set up directories
    file: path={{ lookup('env', 'HOME') }}/.vim/{{ item }} state=directory
    register: file
    with_items: vim_directories

  - name: bootstrap vundle itself
    git: 
      repo={{ item.url }}
      dest={{ lookup('env', 'HOME') }}/.vim/bundle/{{ item.name }}
    with_items: bundle_names

  - name: install vim plugins
    command: vim +PluginInstall +qall
